[package]
name = "udpt-rs"
version = "0.1.0"
authors = ["Naim A. <naim94a@github.com>"]
description = "High performance torrent tracker"

[profile.release]
lto = true

[dependencies]
serde = "1.0.80"
bincode = "1.0.1"
serde_derive = "1.0.80"
actix-web = "0.7.13"
binascii = "0.1.2"